# permissions for end users to view simpledeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simpledeployment-viewer-role
rules:
- apiGroups:
  - simplegroup.mihai.domain
  resources:
  - simpledeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - simplegroup.mihai.domain
  resources:
  - simpledeployments/status
  verbs:
  - get
