# permissions for end users to edit simpledeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simpledeployment-editor-role
rules:
- apiGroups:
  - simplegroup.mihai.domain
  resources:
  - simpledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simplegroup.mihai.domain
  resources:
  - simpledeployments/status
  verbs:
  - get
