apiVersion: simplegroup.mihai.domain/v0
kind: SimpleDeployment
metadata:
  name: sd2
spec:
  replicas: 1
  image: nginx:latest
  ingressInfo:
    #ingressControllerType: nginx
    #ingressClassName: nginx
    host: dev.local
    publicPort: 443
    path: /sd2
    rewriteTarget: /
