apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    homework: simpledeployment
    helm.sh/chart: {{ include "simpledeployment-operator.chart" . }}
    app.kubernetes.io/name: {{ include "simpledeployment-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: sd-controller-manager
  #namespace: sd-sys
