# Default values for simpledeployment-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/mihaialexandrescu/simpledeployment
  tag: v0.1.0
